{"name": "Impossible to get order with invalid track number", "status": "passed", "steps": [{"name": "Impossible to get order", "status": "passed", "start": 1748112660433, "stop": 1748112660512}], "start": 1748112660433, "stop": 1748112660514, "uuid": "27fcbbfe-9b24-4592-9eb9-67d4d9b39e1a", "historyId": "59e744cf3287bd8bbeae277cbef95624", "testCaseId": "59e744cf3287bd8bbeae277cbef95624", "fullName": "tests.test_additional_task.TestsAdditionalTask#test_no_order_with_invalid_track_number", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_additional_task"}, {"name": "subSuite", "value": "TestsAdditionalTask"}, {"name": "host", "value": "Panin-hp"}, {"name": "thread", "value": "19980-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_additional_task"}]}